# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-16 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0002_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('apdated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ManyToManyField(related_name='wish_items', to='login.User')),
            ],
        ),
    ]
