# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-16 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_item_added_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='added_by',
            field=models.IntegerField(default=1),
        ),
    ]
