# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-16 20:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_auto_20161216_0950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='added_by',
        ),
        migrations.AddField(
            model_name='item',
            name='added_by_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='added_by_name',
            field=models.CharField(default='santa', max_length=255),
        ),
    ]
