# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-16 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='User', max_length=255),
        ),
    ]
